#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BoardApp.Resource", IsApplication=true)]

namespace BoardApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int splash_background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int splash = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int strength = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080015
			public const int ActionBar_cancel = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int ActionBar_commit = 2131230740;
			
			// aapt resource value: 0x7f080012
			public const int ActionBar_createThread = 2131230738;
			
			// aapt resource value: 0x7f080002
			public const int CommentListItemView_content = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int CommentListItemView_gravater = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CommentListItemView_writer = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int CommentListItemView_writtenDatetime = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int LoginDialog_email = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int LoginDialog_password = 2131230726;
			
			// aapt resource value: 0x7f08000e
			public const int ThreadOpenActivity_comment = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int ThreadOpenActivity_subject = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int ThreadOpenActivity_tags = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int ThreadViewCommentList = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int ThreadView_commentInput = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int ThreadView_commentSender = 2131230735;
			
			// aapt resource value: 0x7f080013
			public const int action_search = 2131230739;
			
			// aapt resource value: 0x7f080008
			public const int main_view_thread_list = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int textView1 = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int textView2 = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int thread_list_item_opener = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int thread_list_item_recent_update_datetime = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int thread_list_item_subject = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CommentListItemView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginDialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Slash = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int thread_list_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ThreadOpenActivity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ThreadViewActivity = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ThreadOpenActivity_menu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyTheme_Splash = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
