#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BoardApp.Resource", IsApplication=true)]

namespace BoardApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int splash_background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int splash = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int strength = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int CommentListItemView_content = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CommentListItemView_gravater = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int CommentListItemView_writer = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CommentListItemView_writtenDatetime = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int LoginDialog_email = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int LoginDialog_password = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int ThreadViewCommentList = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int ThreadView_commentInput = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int ThreadView_commentSender = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int main_view_thread_list = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int textView1 = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int textView2 = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int thread_list_item_opener = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int thread_list_item_recent_update_datetime = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int thread_list_item_subject = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CommentListItemView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginDialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Slash = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int thread_list_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ThreadViewActivity = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyTheme_Splash = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
